// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Readline = require("bs-readline/src/Readline.js");
var Pervasives = require("bs-platform/lib/js/pervasives.js");

function read(x) {
  return x;
}

function $$eval(x) {
  return x;
}

function print(x) {
  return x;
}

function rep(input) {
  return input;
}

function print_prompt(param) {
  return Pervasives.print_string("user> ");
}

Readline.readline((function (input) {
        console.log(input);
        return Pervasives.print_string("user> ");
      }));

Pervasives.print_string("user> ");

exports.read = read;
exports.$$eval = $$eval;
exports.print = print;
exports.rep = rep;
exports.print_prompt = print_prompt;
/*  Not a pure module */
