// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Readline = require("bs-readline/src/Readline.js");

function read(x) {
  return x;
}

function $$eval(x) {
  return x;
}

function print(x) {
  return x;
}

function rep(input) {
  return input;
}

function prompt(param) {
  console.log("user>");
  return Readline.readline((function (input) {
                console.log(input);
                Readline.close(/* () */0);
                return prompt(/* () */0);
              }));
}

prompt(/* () */0);

exports.read = read;
exports.$$eval = $$eval;
exports.print = print;
exports.rep = rep;
exports.prompt = prompt;
/*  Not a pure module */
